[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lpoppn"
authors = [{name = "Maxime TOMA", email = "maxime.toma@lpo.fr"}]
dynamic = ["version", "description"]
